version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile.app
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  redis_data: